create table "public"."fcm_notifications" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "completed_at" timestamp with time zone,
    "user_id" uuid not null,
    "title" text,
    "body" text,
    "result" text
);


alter table "public"."fcm_notifications" enable row level security;

CREATE UNIQUE INDEX fcm_notifications_pkey ON public.fcm_notifications USING btree (id);

alter table "public"."fcm_notifications" add constraint "fcm_notifications_pkey" PRIMARY KEY using index "fcm_notifications_pkey";

grant delete on table "public"."fcm_notifications" to "anon";

grant insert on table "public"."fcm_notifications" to "anon";

grant references on table "public"."fcm_notifications" to "anon";

grant select on table "public"."fcm_notifications" to "anon";

grant trigger on table "public"."fcm_notifications" to "anon";

grant truncate on table "public"."fcm_notifications" to "anon";

grant update on table "public"."fcm_notifications" to "anon";

grant delete on table "public"."fcm_notifications" to "authenticated";

grant insert on table "public"."fcm_notifications" to "authenticated";

grant references on table "public"."fcm_notifications" to "authenticated";

grant select on table "public"."fcm_notifications" to "authenticated";

grant trigger on table "public"."fcm_notifications" to "authenticated";

grant truncate on table "public"."fcm_notifications" to "authenticated";

grant update on table "public"."fcm_notifications" to "authenticated";

grant delete on table "public"."fcm_notifications" to "service_role";

grant insert on table "public"."fcm_notifications" to "service_role";

grant references on table "public"."fcm_notifications" to "service_role";

grant select on table "public"."fcm_notifications" to "service_role";

grant trigger on table "public"."fcm_notifications" to "service_role";

grant truncate on table "public"."fcm_notifications" to "service_role";

grant update on table "public"."fcm_notifications" to "service_role";


